// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxodiduudsncfbzltcfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14b2RpZHV1ZHNuY2Ziemx0Y2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5NzUxMDMsImV4cCI6MjA5MjU1MTEwM30.FKD5wjYBiw_y5gpj2FK0Igp0K9M2JHbqe_woL2KgjrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
